services:
  posts_service:
    build: ./posts_service
    ports:
      - "127.0.0.1:8001:8000" # Порт, по которому будет доступен Posts Service
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./data/posts.db # Отдельная БД для постов
    volumes:
      - posts_db_data:/app/data


  categories_service:
    build: ./categories_service
    ports:
      - "127.0.0.1:8002:8000" # Порт, по которому будет доступен Categories Service
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./data/categories.db # Отдельная БД для категорий
    volumes:
      - categories_db_data:/app/data

volumes:
  posts_db_data:
  categories_db_data: