services:
  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    ports:
      - "127.0.0.1:15672:15672" # Порт для веб-интерфейса RabbitMQ Management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck: # Проверка готовности RabbitMQ
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5

  posts_service:
    build: ./posts_service
    ports:
      - "127.0.0.1:8001:8000" # Порт, по которому будет доступен Posts Service
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./data/posts.db # Отдельная БД для постов
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - posts_db_data:/app/data
    depends_on:
      categories_service:
        condition: service_started # Posts Service зависит от Categories Service для валидации
      rabbitmq:
        condition: service_healthy


  categories_service:
    build: ./categories_service
    ports:
      - "127.0.0.1:8002:8000" # Порт, по которому будет доступен Categories Service
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./data/categories.db # Отдельная БД для категорий
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - categories_db_data:/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  posts_db_data:
  categories_db_data: